=== mickeypearce/oradew-vscode/resources/oradewrc-schema.json
{
  "title": "JSON schema for Oradew configuration file",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "object",
  "properties": {
    "package.input": {
      "default": [
        "./scripts/**/initial*.sql",
        "./src/**/VIEWS/*.sql",
        "./src/**/TYPES/*.sql",
        "./src/**/TYPE_BODIES/*.sql",
        "./src/**/TRIGGERS/*.sql",
        "./src/**/PACKAGES/*.sql",
        "./src/**/PACKAGE_BODIES/*.sql",
        "./src/**/FUNCTIONS/*.sql",
        "./src/**/PROCEDURES/*.sql",
        "./scripts/**/final*.sql",
        "!./**/*EXCLUDE*.sql"
      ],
      "description": "Glob pattern for packaging files into deploy script file. \nPreserving order, prefix with ! for excluding.",
      "type": "array"
    },
    "package.output": {
      "default": "./deploy/Run.sql",
      "description": "Deploy package output file.",
      "type": "string"
    },
    "package.encoding": {
      "default": "utf8",
      "description": "Deploy file encoding. \n(utf8, win1250, ...)",
      "type": "string"
    },
    "package.templating": {
      "default": false,
      "description": "Package templating of config variables in sql files. \nex.usage in sql code: '${config[\"version.number\"]}'",
      "type": "boolean"
    },
    "source": {
      "default": ["./src/**/*.sql"],
      "description": "Glob pattern for source files.",
      "type": "array"
    },
    "compile.warnings": {
      "default": "NONE",
      "description": "Compilation warning scopes.",
      "type": "string",
      "enum": ["NONE", "ALL", "PERFORMANCE", "INFORMATIONAL", "SEVERE"]
    },
    "compile.force": {
      "default": false,
      "description": "Ignore conflict detection and auto-merge local file changes with DB object when compiling to DEV environment. \nCompilation on other envs is always done with force.",
      "type": "boolean"
    },
    "version.number": {
      "default": "0.0.1",
      "description": "Version number.",
      "type": "string"
    },
    "version.description": {
      "default": "New feature",
      "description": "Version description.",
      "type": "string"
    },
    "version.releaseDate": {
      "default": "2099-01-01",
      "description": "Version release date.",
      "type": "string",
      "format": "date-time"
    },
    "test.input": {
      "default": ["./test/**/*.test.sql"],
      "description": "Glob pattern for tests.",
      "type": "array"
    },
    "import.getDdlFunction": {
      "default": "dbms_metadata.get_ddl",
      "description": "DDL function name. Use your own DB function to customize import of object's DDL. \"DBMS_METADATA.GET_DDL\" by default. \nex.custom DB func.spec.: FUNCTION GetDDL(object_type IN VARCHAR2, name IN VARCHAR2, schema IN VARCHAR2 DEFAULT NULL) RETURN CLOB;",
      "type": "string"
    },
    "generator.define": {
      "default": [
        {
          "label": "#1",
          "description": "Define your generator in oradewrc.json",
          "function": ""
        }
      ],
      "description": "Array of generator definitions.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string",
            "description": "Generator identifier"
          },
          "function": {
            "type": "string",
            "description": "Generator function name on DB. \nex.DB func.spec.: FUNCTION genUpdateStatement(object_type IN VARCHAR2, name IN VARCHAR2, schema IN VARCHAR2, selected_object IN VARCHAR2) RETURN CLOB;"
          },
          "description": {
            "string": "string"
          },
          "output": {
            "description": "File path with generated content. If omitted generated filename is created.",
            "string": "string"
          }
        },
        "required": ["label", "function"]
      }
    }
  }
}

=== mickeypearce/oradew-vscode/test/oradewrc.json
{
  "package.input": [
    "./scripts/**/initial*.sql",
    "./src/**/VIEWS/*.sql",
    "./src/**/TYPES/*.sql",
    "./src/**/TYPE_BODIES/*.sql",
    "./src/**/TRIGGERS/*.sql",
    "./src/**/PACKAGES/*.sql",
    "./src/**/PACKAGE_BODIES/*.sql",
    "./src/**/FUNCTIONS/*.sql",
    "./src/**/PROCEDURES/*.sql",
    "./scripts/**/final*.sql",
    "!./**/*EXCLUDE*.sql"
  ],
  "package.output": "./deploy/Run.sql",
  "package.encoding": "utf8",
  "package.templating": false,
  "source": ["./src/**/*.sql"],
  "compile.warnings": "NONE",
  "compile.force": false,
  "version.number": "0.0.1",
  "version.description": "New feature",
  "version.releaseDate": "2099-01-01",
  "test.input": ["./test/**/*.test.sql"]
}
